recipe: default.v1
language: en
domain: domain

pipeline:

- name: SingleStepLLMCommandGenerator
  llm:
    model_group: rasa_command_generation_model
  flow_retrieval:
      active: false
  prompt_template: prompt/command-generator.jinja2


policies:
  - name: FlowPolicy

assistant_id: 20250321-144941-pointed-font
